# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stratum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import google.protobuf.descriptor_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='stratum.proto',
  package='',
  serialized_pb='\n\rstratum.proto\x1a google/protobuf/descriptor.proto\"\x17\n\tSubscribe\x12\n\n\x02id\x18\x01 \x02(\r\">\n\tAuthorize\x12\n\n\x02id\x18\x01 \x02(\r\x12\x13\n\x0bworker_name\x18\x02 \x02(\x0c\x12\x10\n\x08password\x18\x03 \x01(\x0c\"\xaa\x01\n\x06Notify\x12\x0e\n\x06job_id\x18\x01 \x01(\x0c\x12\x10\n\x08prevhash\x18\x02 \x02(\x0c\x12\x11\n\tcoinbase1\x18\x03 \x02(\x0c\x12\x11\n\tcoinbase2\x18\x04 \x01(\x0c\x12\x15\n\rmerkle_branch\x18\x05 \x03(\x0c\x12\x0f\n\x07version\x18\x06 \x02(\x0c\x12\r\n\x05nbits\x18\x07 \x02(\x0c\x12\r\n\x05ntime\x18\x08 \x02(\x0c\x12\x12\n\nclean_jobs\x18\t \x01(\x08\"l\n\x06Submit\x12\n\n\x02id\x18\x01 \x02(\r\x12\x13\n\x0bworker_name\x18\x02 \x01(\x0c\x12\x0e\n\x06job_id\x18\x03 \x01(\x0c\x12\x13\n\x0b\x65xtranonce2\x18\x04 \x02(\x0c\x12\r\n\x05ntime\x18\x05 \x02(\x0c\x12\r\n\x05nonce\x18\x06 \x02(\x0c\"#\n\rSetDifficulty\x12\x12\n\ndifficulty\x18\x01 \x02(\x04\"9\n\tReconnect\x12\x10\n\x08hostname\x18\x01 \x01(\x0c\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x0c\n\x04wait\x18\x03 \x01(\x05\"\x18\n\nGetVersion\x12\n\n\x02id\x18\x01 \x02(\r\"\t\n\x07Version*\xfd\x02\n\x0bMessageType\x12/\n\x15MessageType_Subscribe\x10\n\x1a\x14\x92\xb5\x18\x10mining.subscribe\x12/\n\x15MessageType_Authorize\x10\x0b\x1a\x14\x92\xb5\x18\x10mining.authorize\x12)\n\x12MessageType_Notify\x10\x0c\x1a\x11\x92\xb5\x18\rmining.notify\x12)\n\x12MessageType_Submit\x10\r\x1a\x11\x92\xb5\x18\rmining.submit\x12\x38\n\x19MessageType_SetDifficulty\x10\x14\x1a\x19\x92\xb5\x18\x15mining.set_difficulty\x12/\n\x15MessageType_Reconnect\x10\x15\x1a\x14\x92\xb5\x18\x10\x63lient.reconnect\x12\x32\n\x16MessageType_GetVersion\x10\x16\x1a\x16\x92\xb5\x18\x12\x63lient.get_version\x12\x17\n\x13MessageType_Version\x10\x17:1\n\x04json\x12!.google.protobuf.EnumValueOptions\x18\xd2\x86\x03 \x01(\tB3\n com.satoshilabs.stratum.protobufB\x0fStratumProtobuf')

_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MessageType_Subscribe', index=0, number=10,
      options=_descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), '\222\265\030\020mining.subscribe'),
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MessageType_Authorize', index=1, number=11,
      options=_descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), '\222\265\030\020mining.authorize'),
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MessageType_Notify', index=2, number=12,
      options=_descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), '\222\265\030\rmining.notify'),
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MessageType_Submit', index=3, number=13,
      options=_descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), '\222\265\030\rmining.submit'),
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MessageType_SetDifficulty', index=4, number=20,
      options=_descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), '\222\265\030\025mining.set_difficulty'),
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MessageType_Reconnect', index=5, number=21,
      options=_descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), '\222\265\030\020client.reconnect'),
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MessageType_GetVersion', index=6, number=22,
      options=_descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), '\222\265\030\022client.get_version'),
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MessageType_Version', index=7, number=23,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=557,
  serialized_end=938,
)

MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
MessageType_Subscribe = 10
MessageType_Authorize = 11
MessageType_Notify = 12
MessageType_Submit = 13
MessageType_SetDifficulty = 20
MessageType_Reconnect = 21
MessageType_GetVersion = 22
MessageType_Version = 23

JSON_FIELD_NUMBER = 50002
json = _descriptor.FieldDescriptor(
  name='json', full_name='json', index=0,
  number=50002, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=unicode("", "utf-8"),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_SUBSCRIBE = _descriptor.Descriptor(
  name='Subscribe',
  full_name='Subscribe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Subscribe.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=51,
  serialized_end=74,
)


_AUTHORIZE = _descriptor.Descriptor(
  name='Authorize',
  full_name='Authorize',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Authorize.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='worker_name', full_name='Authorize.worker_name', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='Authorize.password', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=76,
  serialized_end=138,
)


_NOTIFY = _descriptor.Descriptor(
  name='Notify',
  full_name='Notify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='Notify.job_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prevhash', full_name='Notify.prevhash', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coinbase1', full_name='Notify.coinbase1', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coinbase2', full_name='Notify.coinbase2', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='merkle_branch', full_name='Notify.merkle_branch', index=4,
      number=5, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='Notify.version', index=5,
      number=6, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nbits', full_name='Notify.nbits', index=6,
      number=7, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ntime', full_name='Notify.ntime', index=7,
      number=8, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clean_jobs', full_name='Notify.clean_jobs', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=141,
  serialized_end=311,
)


_SUBMIT = _descriptor.Descriptor(
  name='Submit',
  full_name='Submit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Submit.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='worker_name', full_name='Submit.worker_name', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='job_id', full_name='Submit.job_id', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extranonce2', full_name='Submit.extranonce2', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ntime', full_name='Submit.ntime', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='Submit.nonce', index=5,
      number=6, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=313,
  serialized_end=421,
)


_SETDIFFICULTY = _descriptor.Descriptor(
  name='SetDifficulty',
  full_name='SetDifficulty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='difficulty', full_name='SetDifficulty.difficulty', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=423,
  serialized_end=458,
)


_RECONNECT = _descriptor.Descriptor(
  name='Reconnect',
  full_name='Reconnect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='Reconnect.hostname', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='Reconnect.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wait', full_name='Reconnect.wait', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=460,
  serialized_end=517,
)


_GETVERSION = _descriptor.Descriptor(
  name='GetVersion',
  full_name='GetVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GetVersion.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=519,
  serialized_end=543,
)


_VERSION = _descriptor.Descriptor(
  name='Version',
  full_name='Version',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=545,
  serialized_end=554,
)

DESCRIPTOR.message_types_by_name['Subscribe'] = _SUBSCRIBE
DESCRIPTOR.message_types_by_name['Authorize'] = _AUTHORIZE
DESCRIPTOR.message_types_by_name['Notify'] = _NOTIFY
DESCRIPTOR.message_types_by_name['Submit'] = _SUBMIT
DESCRIPTOR.message_types_by_name['SetDifficulty'] = _SETDIFFICULTY
DESCRIPTOR.message_types_by_name['Reconnect'] = _RECONNECT
DESCRIPTOR.message_types_by_name['GetVersion'] = _GETVERSION
DESCRIPTOR.message_types_by_name['Version'] = _VERSION

class Subscribe(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SUBSCRIBE

  # @@protoc_insertion_point(class_scope:Subscribe)

class Authorize(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTHORIZE

  # @@protoc_insertion_point(class_scope:Authorize)

class Notify(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NOTIFY

  # @@protoc_insertion_point(class_scope:Notify)

class Submit(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SUBMIT

  # @@protoc_insertion_point(class_scope:Submit)

class SetDifficulty(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SETDIFFICULTY

  # @@protoc_insertion_point(class_scope:SetDifficulty)

class Reconnect(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RECONNECT

  # @@protoc_insertion_point(class_scope:Reconnect)

class GetVersion(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETVERSION

  # @@protoc_insertion_point(class_scope:GetVersion)

class Version(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VERSION

  # @@protoc_insertion_point(class_scope:Version)

google.protobuf.descriptor_pb2.EnumValueOptions.RegisterExtension(json)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n com.satoshilabs.stratum.protobufB\017StratumProtobuf')
_MESSAGETYPE.values_by_name["MessageType_Subscribe"].has_options = True
_MESSAGETYPE.values_by_name["MessageType_Subscribe"]._options = _descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), '\222\265\030\020mining.subscribe')
_MESSAGETYPE.values_by_name["MessageType_Authorize"].has_options = True
_MESSAGETYPE.values_by_name["MessageType_Authorize"]._options = _descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), '\222\265\030\020mining.authorize')
_MESSAGETYPE.values_by_name["MessageType_Notify"].has_options = True
_MESSAGETYPE.values_by_name["MessageType_Notify"]._options = _descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), '\222\265\030\rmining.notify')
_MESSAGETYPE.values_by_name["MessageType_Submit"].has_options = True
_MESSAGETYPE.values_by_name["MessageType_Submit"]._options = _descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), '\222\265\030\rmining.submit')
_MESSAGETYPE.values_by_name["MessageType_SetDifficulty"].has_options = True
_MESSAGETYPE.values_by_name["MessageType_SetDifficulty"]._options = _descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), '\222\265\030\025mining.set_difficulty')
_MESSAGETYPE.values_by_name["MessageType_Reconnect"].has_options = True
_MESSAGETYPE.values_by_name["MessageType_Reconnect"]._options = _descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), '\222\265\030\020client.reconnect')
_MESSAGETYPE.values_by_name["MessageType_GetVersion"].has_options = True
_MESSAGETYPE.values_by_name["MessageType_GetVersion"]._options = _descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), '\222\265\030\022client.get_version')
# @@protoc_insertion_point(module_scope)
